ShopOnline/Areas/Admin/Controllers/CRUDblogController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ShopOnline.Models;
using System.IO;
using PagedList;
using PagedList.Mvc;
using ShopOnline.Areas.Admin.Patern.Facade;
using ShopOnline.Areas.Admin.Patern.Strategy.CreateBlog;

namespace ShopOnline.Areas.Admin.Controllers
{
    [Authorize]
    public class CRUDblogController : Controller
    {
        
        menfashionEntities db = DatabaseContext.Instance.GetDbContext();
        private ArticleFacade articleFacade = new ArticleFacade();

        //hàm check đuôi file 
        private IImageStrategy GetImageStrategy(string extension)
        {
            switch (extension.ToLower())
            {
                case ".jpg":
                case ".jpeg":
                    return new JpgImageStrategy();
                case ".png":
                    return new PngImageStrategy();
                default:
                    throw new NotSupportedException("Unsupported image format");
            }
        }


        public ActionResult Index(int? page, string searching)
        {
            var pageNumber = page ?? 1;
            var pageSize = 10;
            var article = db.Articles.Where(model => model.title.Contains(searching) || searching == null).OrderByDescending(model => model.publicDate).Include(model => model.ProductCategory).ToPagedList(pageNumber, pageSize);
            return View(article);
        }

        //CREATE
        [HttpGet]
        [ValidateInput(false)]
        public ActionResult Create()
        {
            ViewBag.categoryId = new SelectList(db.ProductCategories, "categoryId", "categoryName");
            return View();
        }
        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Article article, HttpPostedFileBase uploadFile)
        {
            //try
            //{
            //    // Xử lí ảnh
            //    var fileName = Path.GetFileName(uploadFile.FileName);
            //    var path = Path.Combine(Server.MapPath("~/Content/img/blog"), fileName);
            //    string extension = Path.GetExtension(uploadFile.FileName);

            //    if (extension.ToLower() == ".jpg" || extension.ToLower() == ".jpeg" || extension.ToLower() == ".png")
            //    {
            //        if (uploadFile == null)
            //        {
            //            ModelState.AddModelError("", "Error while file uploading.");
            //        }
            //        else
            //        {

            //            article.image = "~/Content/img/blog/" + fileName;
            //            article.userName = Session["userNameAdmin"].ToString();
            //            article.publicDate = DateTime.Now;
            //            article.status = true;
            //            db.Articles.Add(article);
            //            if (db.SaveChanges() > 0)
            //            {
            //                uploadFile.SaveAs(path);
            //                ModelState.Clear();
            //                TempData["msgCreate"] = "Successfully create a new blog!";
            //                return RedirectToAction("Index");
            //            }
            //        }
            //    }
            //    else
            //    {
            //        ModelState.AddModelError("", "Invalid File Type");
            //    }
            //    ViewBag.categoryId = new SelectList(db.ProductCategories, "categoryId", "categoryName", article.categoryId);
            //    return View(article);
            //}
            //catch (Exception ex)
            //{
            //    TempData["msgCreatefailed"] = "Create failed! " + ex.Message;
            //    return RedirectToAction("Create");
            //}
        
            try
    {
        // Xử lí ảnh
        var fileName = Path.GetFileName(uploadFile.FileName);
        var path = Path.Combine(Server.MapPath("~/Content/img/blog"), fileName);
        string extension = Path.GetExtension(uploadFile.FileName);

        if (extension.ToLower() == ".jpg" || extension.ToLower() == ".jpeg" || extension.ToLower() == ".png")
        {
            if (uploadFile == null)
            {
                ModelState.AddModelError("", "Error while file uploading.");
            }
            else
            {
                // Sử dụng mẫu thiết kế Strategy xử lý ảnh phù hợp
                IImageStrategy imageStrategy = GetImageStrategy(extension);
                article.image = imageStrategy.GetImagePath(fileName);

                article.userName = Session["userNameAdmin"].ToString();
                article.publicDate = DateTime.Now;
                article.status = true;
                db.Articles.Add(article);
                if (db.SaveChanges() > 0)
                {
                    uploadFile.SaveAs(path);
                    ModelState.Clear();
                    TempData["msgCreate"] = "Successfully create a new blog!";
                    return RedirectToAction("Index");
                }
            }
        }
        else
        {
            ModelState.AddModelError("", "Invalid File Type");
        }
        ViewBag.categoryId = new SelectList(db.ProductCategories, "categoryId", "categoryName", article.categoryId);
        return View(article);
    }
    catch (Exception ex)
    {
        TempData["msgCreatefailed"] = "Create failed! " + ex.Message;
        return RedirectToAction("Create");
    }


        }

        //EDIT
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            Article article = db.Articles.Find(id);
            Session["imgPath"] = article.image;
            ViewBag.categoryId = new SelectList(db.ProductCategories, "categoryId", "categoryName", article.categoryId);
            return View(article);
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult Edit(Article article, HttpPostedFileBase uploadFile, FormCollection collection)
        {
            try
            {
                var contentTemp = collection["des"]; // Lấy giá trị nhập ở input content
                if (ModelState.IsValid)
                {
                    if (uploadFile != null)
                    {
                        var fileName = Path.GetFileName(uploadFile.FileName);
                        var path = Path.Combine(Server.MapPath("~/Content/img/blog"), fileName);

                        article.image = "~/Content/img/blog/" + fileName;
                        article.content = contentTemp;
                        db.Entry(article).State = EntityState.Modified;
                        string oldImgPath = Request.MapPath(Session["imgPath"].ToString());
                        if (db.SaveChanges() > 0)
                        {
                            TempData["msgEdit"] = "Successfully edited product has ID: " + article.articleId;
                            uploadFile.SaveAs(path);
                            if (System.IO.File.Exists(oldImgPath))
                            {
                                System.IO.File.Delete(oldImgPath);
                            }
                        }
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        article.content = contentTemp;
                        article.image = Session["imgPath"].ToString();
                        db.Entry(article).State = EntityState.Modified;
                        if (db.SaveChanges() > 0)
                        {
                            TempData["msgEdit"] = "Successfully edited product has ID: " + article.articleId;
                            return RedirectToAction("index");
                        }
                    }
                }
                ViewBag.categoryId = new SelectList(db.ProductCategories, "categoryId", "categoryName", article.categoryId);
                return View(article);
            }
            catch(Exception ex)
            {
                TempData["msgEditFailed"] = "Edit failed! " + ex.Message;
                return RedirectToAction("Index");
            }
        }
        //DELETE
        public ActionResult Delete(int? id)
        {
            //try
            //{
            //    Article article = db.Articles.Find(id);
            //    string currentImg = Request.MapPath(article.image);
            //    if (System.IO.File.Exists(currentImg))
            //    {
            //        System.IO.File.Delete(currentImg);
            //    }
            //    db.Articles.Remove(article);
            //    db.SaveChanges();
            //    return RedirectToAction("Index");
            //}
            //catch (Exception ex)
            //{
            //    TempData["msgDelete"] = "Can't delete this! " + ex.Message;
            //    return RedirectToAction("Index");
            //}
            bool isDeleted = articleFacade.DeleteArticle(id);
            if (!isDeleted)
            {
                TempData["msgDelete"] = "Can't delete this article.";
            }

            return RedirectToAction("Index");
        }

    }
}

ShopOnline/Areas/Admin/Views/CRUDblog/Create.cshtml
@model ShopOnline.Models.Article
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutDashBoard.cshtml";
}

<div class="page-breadcrumb">
    <div class="row">
        <div class="col-7 align-self-center">
            <h4 class="page-title text-truncate text-dark font-weight-medium mb-1">Blogs</h4>
            <div class="d-flex align-items-center">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb m-0 p-0">
                        <li class="breadcrumb-item"><a href="~/Admin/DashBoard/Index" class="text-muted">Home</a></li>
                        <li class="breadcrumb-item text-muted active" aria-current="page">Create blog</li>
                    </ol>
                </nav>
            </div>
        </div>
        <div class="col-5 align-self-center">
            <div class="customize-input float-right">
                <select class="custom-select custom-select-set form-control bg-white border-0 custom-shadow custom-radius">
                    <option selected>Aug 19</option>
                    <option value="1">July 19</option>
                    <option value="2">Jun 19</option>
                </select>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">Create blog</h3>
                    @if (TempData["msgCreatefailed"] != null)
                    {
                        <div class="alert alert-danger alert-dismissible bg-danger text-white border-0 fade show" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">×</span>
                            </button>
                            @TempData["msgCreatefailed"]
                        </div>
                    }
                    @using (Html.BeginForm("Create", "CRUDblog", FormMethod.Post, new { @id = "form-1", @enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="form-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="title">Title</label>
                                        <input type="text" class="form-control" name="title" id="title" />
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="shortDescription">Short description</label>
                                        <input type="text" class="form-control" name="shortDescription" id="shortDescription" />
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="content">content</label>
                                        <textarea name="content" class="form-control textareaTinym" id="content"></textarea>
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="">Category</label>
                                        @Html.DropDownList("categoryId", null, htmlAttributes: new { @class = "form-control" })
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="image">Image</label>
                                        <img id="file-ip-1-preview" style="margin-bottom: 10px;" />
                                        <input type="file" name="uploadFile" class="form-control-file" id="image" onchange="showPreview(event);" />
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-actions">
                            <div class="text-right">
                                <button type="submit" class="btn btn-info">Submit</button>
                                <button type="reset" class="btn btn-dark">Reset</button>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/Content/js/validator.js"></script>
<script>
    Validator({
        form: '#form-1',
        formGroupSelector: '.form-group',
        errorSelector: '.form-message',
        rules: [
            Validator.isRequired('#title'),
            Validator.isRequired('#image'),
        ],
    });

    function showPreview(event) {
        if (event.target.files.length > 0) {
            var src = URL.createObjectURL(event.target.files[0]);
            var preview = document.getElementById("file-ip-1-preview");
            preview.src = src;
            preview.style.display = "block";
            preview.style.height = "200px";
        }
    }
</script>

ShopOnline/Areas/Admin/Views/CRUDblog/Edit.cshtml
@model ShopOnline.Models.Article

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutDashBoard.cshtml";
}
<div class="page-breadcrumb">
    <div class="row">
        <div class="col-7 align-self-center">
            <h4 class="page-title text-truncate text-dark font-weight-medium mb-1">Edit product</h4>
            <div class="d-flex align-items-center">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb m-0 p-0">
                        <li class="breadcrumb-item"><a href="~/Admin/CRUDblog/Index" class="text-muted">Blog list</a></li>
                        <li class="breadcrumb-item text-muted active" aria-current="page">Edit</li>
                    </ol>
                </nav>
            </div>
        </div>
        <div class="col-5 align-self-center">
            <div class="customize-input float-right">
                <select class="custom-select custom-select-set form-control bg-white border-0 custom-shadow custom-radius">
                    <option selected>Aug 19</option>
                    <option value="1">July 19</option>
                    <option value="2">Jun 19</option>
                </select>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">Edit blog</h3>
                    @using (Html.BeginForm("Edit", "CRUDblog", FormMethod.Post, new { @id = "form-1", @enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-body">
                            @Html.HiddenFor(model => model.publicDate)
                            @Html.HiddenFor(model => model.articleId)
                            @Html.HiddenFor(model => model.userName)

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="title">Title</label>
                                        @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control", @id = "title" } })
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="productName">Desciption</label>
                                        @*@Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control textareaTinym", @id = "description" } })*@
                                        <div style="padding:10px; border:1px solid;margin-bottom:10px">
                                            @if(Model.content.Length < 500)
                                            {
                                                 @Html.Raw(Model.content)
                                            }
                                            else
                                            {
                                                @Html.Raw(Model.content.Substring(0, 500)) <span> ...</span>
                                            }
                                            
                                        </div>
                                        <textarea class="form-group" name="des" id="content"></textarea>
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="shortDescription">Short description</label>
                                        @Html.EditorFor(model => model.shortDescription, new { htmlAttributes = new { @class = "form-control", @id = "shortDescription" } })
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="productName">Is checked</label>
                                        @Html.EditorFor(model => model.status, new { htmlAttributes = new { @class = "form-control", @id = "status" } })
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="productName">Category</label>
                                        @Html.DropDownList("categoryId", null, htmlAttributes: new { @class = "form-control" })
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="productName">Image</label>
                                        <img src=@Url.Content(Model.image) class="img-thumbnail" width="100%" style="display:block; margin-bottom:10px" id="imagePreview" />
                                        <input type="file" name="uploadFile" class="form-control-file" id="image" accept="image/jpeg, image/png" onclick="defaultBtnActive()" />
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-actions">
                            <div class="text-right">
                                <button type="submit" class="btn waves-effect waves-light btn-success">Edit</button>
                                <a href="~/Admin/CRUDblog/Index" class="btn btn-info">Back to list</a>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/Content/js/validator.js"></script>
<script>
    Validator({
        form: '#form-1',
        formGroupSelector: '.form-group',
        errorSelector: '.form-message',
        rules: [
            Validator.isRequired('#title')
        ],
    });
</script>

<script>
    const inputImg = document.querySelector("#image");
    const img = document.querySelector("#imagePreview");

    function defaultBtnActive() {
        inputImg.change();
    }
    inputImg.addEventListener("change", function () {
        const file = this.files[0];
        if (file) {
            const reader = new FileReader();
            reader.onload = function () {
                const result = reader.result;
                img.src = result;
            }
            reader.readAsDataURL(file);
        }
    });
</script>

ShopOnline/Areas/Admin/Views/CRUDblog/Index.cshtml
@using ShopOnline.Models
@using PagedList.Mvc
@model PagedList.PagedList<Article>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutDashBoard.cshtml";
}

<div class="page-breadcrumb">
    <div class="row">
        <div class="col-7 align-self-center">
            <h4 class="page-title text-truncate text-dark font-weight-medium mb-1">Blog manage</h4>
            <div class="d-flex align-items-center">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb m-0 p-0">
                        <li class="breadcrumb-item"><a href="~/Admin/DashBoard/Index">Dash board</a></li>
                        <li class="breadcrumb-item active">Blog list</li>
                    </ol>
                </nav>
            </div>
        </div>
        <div class="col-5 align-self-center">
            <div class="customize-input float-right">
                <select class="custom-select custom-select-set form-control bg-white border-0 custom-shadow custom-radius">
                    <option selected>Aug 19</option>
                    <option value="1">July 19</option>
                    <option value="2">Jun 19</option>
                </select>
            </div>
        </div>
    </div>
</div>
<br />

<div class="card-body">
    <h3 class="text-dark text-uppercase card-title">Blog</h3>
       @if (TempData["msgCreate"] != null)
        {
        <div class="alert alert-success alert-dismissible bg-success text-white border-0 fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
                @TempData["msgCreate"]
         </div>
        }
        @if (TempData["msgEdit"] != null)
        {
        <div class="alert alert-success alert-dismissible bg-success text-white border-0 fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
                @TempData["msgEdit"]
         </div>
        }
        @if (TempData["msgEditFailed"] != null)
        {
            <div class="alert alert-danger alert-dismissible bg-danger text-white border-0 fade show" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                @TempData["msgEditFailed"]
            </div>
        }
        @if (TempData["msgDelete"] != null)
        {
            <div class="alert alert-danger alert-dismissible bg-danger text-white border-0 fade show" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                @TempData["msgDelete"]
            </div>
        }

    <hr />
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="dataTables_length" id="zero_config_length" style="display:flex"><label style="display:inherit;">Show <select name="zero_config_length" aria-controls="zero_config" class="form-control form-control-sm" style="position: relative; bottom: 3px;"><option value="10">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select> entries</label></div>

        </div>
        <div class="col-sm-12 col-md-6">
            <div id="zero_config_filter" class="dataTables_filter" style="text-align: right;">
                <label style="display: flex; align-items: center;justify-content: flex-end;">
                    Search:
                    @using (Html.BeginForm("Index", "CRUDblog", FormMethod.Get, new { @style = "display: flex; align-items: center;" }))
                    {
                        <input type="search" name="searching" class="form-control form-control-sm" aria-controls="zero_config" style="width:auto" />
                        <input type="submit" value="Search" />
                    }
                </label>
            </div>

        </div>
    </div>
    <div class="table-responsive">

        <table class="table">
            <thead class="thead-light">
                <tr>
                    <th scope="col" class="text-center">STT</th>
                    <th class="text-center">Title</th>
                    <th class="text-center">Public date</th>
                    <th class="text-center">Author</th>
                    <th class="text-center">Category</th>
                    <th class="text-center">Checked</th>
                    <th class="text-center">Feature</th>
                </tr>
            </thead>
            <tbody>
                @if(Model.Count == 0)
                {
                    <tr>
                        <td colspan="8">No match any document</td>
                    </tr>
                }
                else
                {
                    int temp = 1;
                    foreach (var i in Model)
                    {
                        <tr>
                            <th scope="row" class="text-center font-weight-medium">@temp</th>
                            <td>@i.title</td>
                            <td class="text-center">@i.publicDate</td>
                            <td class="text-center">@i.userName</td>
                            <td class="text-center">@i.ProductCategory.categoryName</td>
                            <td class="text-center">
                                @if (i.status == true)
                                {
                                    <i class="fa fa-circle text-success font-12" data-toggle="tooltip" data-placement="top" title="Checked"></i> }
                                else
                                {
                                    <i class="fa fa-circle text-danger font-12" data-toggle="tooltip" data-placement="top" title="Unchecked"></i>}
                            </td>
                            <td width="170px">
                                <a href="@Url.Action("Edit", "CRUDblog", new { id = i.articleId})" class="btn waves-effect waves-light btn-primary">Edit</a>
                                <a href="@Url.Action("Delete", "CRUDblog", new { id = i.articleId})" class="btn waves-effect waves-light btn-danger" onclick="return confirm('Are you sure you want to delete this?')">Delete</a>
                            </td>
                        </tr>
                        temp++;
                    }
                }

            </tbody>
        </table>
    </div>

    <div class="row" style=" align-items: center">
        <div class="col-sm-12 col-md-5">
            <div class="dataTables_info" id="zero_config_info" role="status" aria-live="polite">Showing 1 to 10 of 57 entries</div>
        </div>
        <div class="col-sm-12 col-md-7">
            <div class="dataTables_paginate paging_simple_numbers" id="default_order_paginate">
                @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }), new PagedListRenderOptions() { LiElementClasses = new List<string> { "paginate_button", "page-item" } })
            </div>
        </div>
    </div>
</div>

<style>
    .page-item a {
        display: block;
        padding: .5rem .75rem;
        margin-left: -1px;
        line-height: 1.25;
        color: #5f76e8;
        background-color: #fff;
        border: 1px solid #dee2e6;
    }

    .pagination {
        margin: 2px 0;
        white-space: nowrap;
        justify-content: flex-end;
    }
</style>