ShopOnline/Areas/Admin/Controllers/CRUDproductController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ShopOnline.Models;
using System.IO;
using PagedList;
using PagedList.Mvc;
using ShopOnline.Areas.Admin.Patern.Facade;
using ShopOnline.Areas.Admin.Patern.Facade.Products;

namespace ShopOnline.Areas.Admin.Controllers
{
    [Authorize]
    public class CRUDproductController : Controller
    {
        menfashionEntities db = DatabaseContext.Instance.GetDbContext();
        private ProductFacade productFacade = new ProductFacade();
        private ProductService productService = new ProductService();


        public ActionResult Index(int? page, string searching)
        {
            var pageNumber = page ?? 1;
            var pageSize = 10;
            var products = db.Products.Where(model => model.productName.Contains(searching) || searching == null).OrderByDescending(model => model.dateCreate).Include(model => model.Member).Include(model => model.ProductCategory).ToPagedList(pageNumber, pageSize);
            return View(products);
        }

        //CREATE
        [HttpGet]
        [ValidateInput(false)]
        public ActionResult Create()
        {
            ViewBag.categoryId = new SelectList(db.ProductCategories, "categoryId", "categoryName");
            return View();
        }
        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Product product, HttpPostedFileBase uploadFile)
        {
            //try
            //{
            //    var productName = product.productName.Trim();
            //    // Lấy tên sản phẩm để kiểm tra có trùng k
            //    var check = db.Products.SingleOrDefault(model => model.productName == productName);
            //    // Xử lí ảnh
            //    var fileName = Path.GetFileName(uploadFile.FileName);
            //    var path = Path.Combine(Server.MapPath("~/Content/img/product"), fileName);
            //    string extension = Path.GetExtension(uploadFile.FileName);

            //    if (extension.ToLower() == ".jpg" || extension.ToLower() == ".jpeg" || extension.ToLower() == ".png")
            //    {
            //        if (check != null)
            //        {
            //            ModelState.AddModelError("", "Product name already exists");
            //        }
            //        else
            //        {
            //            if (uploadFile == null)
            //            {
            //                ModelState.AddModelError("", "Error while file uploading.");
            //            }
            //            else
            //            {
            //                if (product.discount >= 100)
            //                {
            //                    ModelState.AddModelError("", "Discount  percent must less than 100.");
            //                }
            //                else
            //                {
            //                    product.productName = product.productName.Trim();
            //                    product.brand = product.brand.Trim();
            //                    product.image = "~/Content/img/product/" + fileName;
            //                    product.userName = Session["userNameAdmin"].ToString();
            //                    product.dateCreate = DateTime.Now;

            //                    product.status = true;


            //                    db.Products.Add(product);
            //                    if (db.SaveChanges() > 0)
            //                    {
            //                        uploadFile.SaveAs(path);
            //                        ModelState.Clear();
            //                        TempData["msgCreate"] = "Successfully create a new product!";
            //                        return RedirectToAction("Index");
            //                    }
            //                }
            //            }
            //        }

            //    }
            //    else
            //    {
            //        ModelState.AddModelError("", "Invalid File Type");
            //    }
            //    ViewBag.categoryId = new SelectList(db.ProductCategories, "categoryId", "categoryName", product.categoryId);
            //    return View(product);
            //}
            //catch (Exception ex)
            //{
            //    TempData["msgCreatefailed"] = "Create failed! " + ex.Message;
            //    return RedirectToAction("Create");
            //}

            try
            {
                productService.CreateProduct(product, uploadFile);
                TempData["msgCreate"] = "Successfully create a new product!";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["msgCreatefailed"] = "Create failed! " + ex.Message;
                return RedirectToAction("Create");
            }


        }

        //EDIT
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            Product product = db.Products.Find(id);
            Session["imgPath"] = product.image;
            ViewBag.categoryId = new SelectList(db.ProductCategories, "categoryId", "categoryName", product.categoryId);
            return View(product);
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult Edit(Product product, HttpPostedFileBase uploadFile, FormCollection collection)
        {
            try
            {
                var descriptiontemp = collection["des"];
                if (ModelState.IsValid)
                {
                    if (uploadFile != null)
                    {
                        var fileName = Path.GetFileName(uploadFile.FileName);
                        var path = Path.Combine(Server.MapPath("~/Content/img/product"), fileName);

                        product.image = "~/Content/img/product/" + fileName;
                        product.description = descriptiontemp;
                        db.Entry(product).State = EntityState.Modified;
                        string oldImgPath = Request.MapPath(Session["imgPath"].ToString());
                        if (db.SaveChanges() > 0)
                        {
                            TempData["msgEdit"] = "Successfully edited product " + product.productName;
                            uploadFile.SaveAs(path);
                            if (System.IO.File.Exists(oldImgPath))
                            {
                                System.IO.File.Delete(oldImgPath);
                            }
                        }
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        product.description = descriptiontemp;
                        product.image = Session["imgPath"].ToString();
                        db.Entry(product).State = EntityState.Modified;
                        if (db.SaveChanges() > 0)
                        {
                            TempData["msgEdit"] = "Successfully edited product has ID: " + product.productId;
                            return RedirectToAction("index");
                        }
                    }
                }
                ViewBag.categoryId = new SelectList(db.ProductCategories, "categoryId", "categoryName", product.categoryId);
                return View(product);
            }
            catch(Exception ex)
            {
                TempData["msgEditFailed"] = "Edit failed! " + ex.Message;
                return RedirectToAction("Index");
            }
        }

        //DELETE
        public ActionResult Delete(int? id)
        {
            //try
            //{
            //    var checkInvoice = db.InvoinceDetails.FirstOrDefault(model => model.productId == id);
            //    // Kiểm tra xem với mã Product có tồn tại trong bảng InvoinceDetail không?
            //    if (checkInvoice != null) // Nếu có giá trị thì xuất thông báo lỗi
            //    {
            //        TempData["msgDelete"] = "Can't delete this!";
            //        return RedirectToAction("Index");
            //    }
            //    else
            //    {
            //        Product product = db.Products.Find(id);
            //        string currentImg = Request.MapPath(product.image);
            //        if (System.IO.File.Exists(currentImg))
            //        {
            //            System.IO.File.Delete(currentImg);
            //        }
            //        db.Products.Remove(product);
            //        db.SaveChanges();
            //        return RedirectToAction("Index");
            //    }
            //}
            //catch (Exception ex)
            //{
            //    TempData["msgDelete"] = "Can't delete this! " + ex.Message;
            //    return RedirectToAction("Index");
            //}
            try
            {
                if (productFacade.CanDeleteProduct(id))
                {
                    TempData["msgDelete"] = "Can't delete this!";
                    return RedirectToAction("Index");
                }
                else
                {
                    productFacade.DeleteProduct(id);
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                TempData["msgDelete"] = "Can't delete this! " + ex.Message;
                return RedirectToAction("Index");
            }
        }
    }

    }

ShopOnline/Areas/Admin/Views/CRUDproduct/Create.cshtml
@model ShopOnline.Models.Product
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutDashBoard.cshtml";
}
<div class="page-breadcrumb">
    <div class="row">
        <div class="col-7 align-self-center">
            <h4 class="page-title text-truncate text-dark font-weight-medium mb-1">Product</h4>
            <div class="d-flex align-items-center">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb m-0 p-0">
                        <li class="breadcrumb-item"><a href="~/Admin/DashBoard/Index" class="text-muted">Home</a></li>
                        <li class="breadcrumb-item text-muted active" aria-current="page">Create product</li>
                    </ol>
                </nav>
            </div>
        </div>
        <div class="col-5 align-self-center">
            <div class="customize-input float-right">
                <select class="custom-select custom-select-set form-control bg-white border-0 custom-shadow custom-radius">
                    <option selected>Aug 19</option>
                    <option value="1">July 19</option>
                    <option value="2">Jun 19</option>
                </select>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">Create product</h3>
                    @if (TempData["msgCreatefailed"] != null)
                    {
                        <div class="alert alert-danger alert-dismissible bg-danger text-white border-0 fade show" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">×</span>
                            </button>
                            @TempData["msgCreatefailed"]
                        </div>
                    }
                    @using (Html.BeginForm("Create", "CRUDproduct", FormMethod.Post, new { @id = "form-1", @enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="form-body">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="productName">Product name</label>
                                        <input type="text" class="form-control" name="productName" id="productName" />
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="brand">Brand</label>
                                        <input type="text" class="form-control" name="brand" id="brand" />
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                            </div>


                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="">Category</label>
                                        @Html.DropDownList("categoryId", null, htmlAttributes: new { @class = "form-control" })
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="quanlity">Quality</label>
                                        <input type="number" class="form-control" name="quanlity" id="quanlity" />
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="price">Price</label>
                                        <input type="number" class="form-control" name="price" id="price" />
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="discount">Discount</label>
                                        <input type="number" class="form-control" name="discount" id="discount" />
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="description">Description</label>
                                        <textarea name="description" class="form-control textareaTinym" id="description"></textarea>
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="image">Image</label>
                                        <img id="file-ip-1-preview" style="margin-bottom: 10px" />
                                        <input type="file" name="uploadFile" class="form-control-file" id="image" onchange="showPreview(event);" />
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-actions">
                            <div class="text-right">
                                <button type="submit" class="btn btn-info">Submit</button>
                                <button type="reset" class="btn btn-dark">Reset</button>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/Content/js/validator.js"></script>
<script>
    Validator({
        form: '#form-1',
        formGroupSelector: '.form-group',
        errorSelector: '.form-message',
        rules: [
            Validator.isRequired('#productName'),
            Validator.isRequired('#price'),
            Validator.isRequired('#image'),
            Validator.isRequired('#discount'),
            Validator.isRequired('#quanlity'),
            Validator.isRequired('#brand'),
        ],
    });

    function showPreview(event) {
        if (event.target.files.length > 0) {
            var src = URL.createObjectURL(event.target.files[0]);
            var preview = document.getElementById("file-ip-1-preview");
            preview.src = src;
            preview.style.display = "block";
            preview.style.height = "200px";
        }
    }
</script>

ShopOnline/Areas/Admin/Views/CRUDproduct/Edit.cshtml
@model ShopOnline.Models.Product
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutDashBoard.cshtml";
}

<div class="page-breadcrumb">
    <div class="row">
        <div class="col-7 align-self-center">
            <h4 class="page-title text-truncate text-dark font-weight-medium mb-1">Edit product</h4>
            <div class="d-flex align-items-center">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb m-0 p-0">
                        <li class="breadcrumb-item"><a href="~/Admin/CRUDproduct/Index" class="text-muted">Product list</a></li>
                        <li class="breadcrumb-item text-muted active" aria-current="page">Edit</li>
                    </ol>
                </nav>
            </div>
        </div>
        <div class="col-5 align-self-center">
            <div class="customize-input float-right">
                <select class="custom-select custom-select-set form-control bg-white border-0 custom-shadow custom-radius">
                    <option selected>Aug 19</option>
                    <option value="1">July 19</option>
                    <option value="2">Jun 19</option>
                </select>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">Edit product</h3>
                    @using (Html.BeginForm("Edit", "CRUDproduct", FormMethod.Post, new { @id = "form-1", @enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-body">
                            @Html.HiddenFor(model => model.productId)
                            @Html.HiddenFor(model => model.dateCreate)
                            @Html.HiddenFor(model => model.userName)
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="productName">Product name</label>
                                        @Html.EditorFor(model => model.productName, new { htmlAttributes = new { @class = "form-control", @id = "productName" } })
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="productName">Image</label>
                                        <img src=@Url.Content(Model.image) class="img-thumbnail" width="20%" style="display:block; margin-bottom:10px" id="imagePreview" />
                                        <input type="file" name="uploadFile" class="form-control-file" id="image" accept="image/jpeg, image/png" onclick="defaultBtnActive()" />
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="productName">Desciption</label>
                                        @*@Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control textareaTinym", @id = "description" } })*@
                                        <div style="padding:10px; border:1px solid;margin-bottom:10px">
                                            @Html.Raw(Model.description)
                                        </div>
                                        <textarea class="form-group" name="des" id="description"></textarea>
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="productName">Price</label>
                                        @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control", @id = "price" } })
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="productName">Discount</label>
                                        @Html.EditorFor(model => model.discount, new { htmlAttributes = new { @class = "form-control", @id = "discount" } })
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="productName">Brand</label>
                                        @Html.EditorFor(model => model.brand, new { htmlAttributes = new { @class = "form-control", @id = "brand" } })
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="productName">Quality</label>
                                        @Html.EditorFor(model => model.quanlity, new { htmlAttributes = new { @class = "form-control", @id = "quanlity" } })
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="productName">Is checked</label>
                                        @Html.EditorFor(model => model.status, new { htmlAttributes = new { @class = "form-control", @id = "status" } })
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="productName">Category</label>
                                        @Html.DropDownList("categoryId", null, htmlAttributes: new { @class = "form-control" })
                                        <span class="form-message"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-actions">
                            <div class="text-right">
                                <button type="submit" class="btn waves-effect waves-light btn-success">Edit</button>
                                <a href="~/Admin/CRUDproduct/Index" class="btn btn-info">Back to list</a>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/Content/js/validator.js"></script>
<script>
    Validator({
        form: '#form-1',
        formGroupSelector: '.form-group',
        errorSelector: '.form-message',
        rules: [
            Validator.isRequired('#productName'),
            Validator.isRequired('#price'),
            Validator.isRequired('#discount'),
            Validator.isRequired('#quanlity'),
            Validator.isRequired('#brand'),
            Validator.isRequired('#status')
        ],
    });
</script>

<script>
        const inputImg = document.querySelector("#image");
        const img = document.querySelector("#imagePreview");  
    
         function defaultBtnActive(){
             inputImg.change();
         }
            inputImg.addEventListener("change", function(){
           const file = this.files[0];
           if(file){
             const reader = new FileReader();
             reader.onload = function(){
               const result = reader.result;
               img.src = result;
               }
             reader.readAsDataURL(file);
           }
         });
</script>